# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: iOS Testsuite

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.eslint*'

  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.eslint*'

permissions:
  contents: read

jobs:
  build:
    name: iOS Build (cordova-ios@${{ matrix.cordova_ios }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    strategy:
      matrix:
        include:
          - cordova_ios: 7.x
            os: macos-14
            xcode: 15.4
          - cordova_ios: 8.x
            os: macos-15
            xcode: 16.4

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20

      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Build plugin in sample app
        run: |
          npm ci
          npm i -g cordova@12.0.0

          APP_DIR="$RUNNER_TEMP/ios-test-app"
          cordova create "$APP_DIR" io.cordova.screenorientation.test ScreenOrientationTest

          cd "$APP_DIR"
          cordova platform add "ios@${{ matrix.cordova_ios }}"
          cordova plugin add "$GITHUB_WORKSPACE"
          cordova build ios --debug --emulator --no-telemetry
